"""init

Revision ID: f527c322e9bf
Revises: 
Create Date: 2025-08-09 10:17:04.617905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f527c322e9bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt_lista_negra',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jwt_lista_negra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jwt_lista_negra_jti'), ['jti'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=80), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_usuario')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_correo'), ['correo'], unique=True)

    op.create_table('archivos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('propietario_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('tipo_mime', sa.String(length=120), nullable=True),
    sa.Column('tamano_bytes', sa.BigInteger(), nullable=True),
    sa.Column('backend_almacenamiento', sa.String(length=20), nullable=False),
    sa.Column('ruta_almacenamiento', sa.String(length=500), nullable=True),
    sa.Column('blob_cifrado', sa.LargeBinary(), nullable=True),
    sa.Column('dek_envuelta', sa.LargeBinary(), nullable=False),
    sa.Column('cifrado', sa.String(length=50), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('tag', sa.LargeBinary(), nullable=False),
    sa.Column('metadatos', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['propietario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archivos_propietario_id'), ['propietario_id'], unique=False)

    op.create_table('claves_cifrado_usuarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('etiqueta', sa.String(length=100), nullable=False),
    sa.Column('uek_envuelta', sa.LargeBinary(), nullable=False),
    sa.Column('kdf', sa.String(length=50), nullable=False),
    sa.Column('kdf_salt', sa.LargeBinary(), nullable=True),
    sa.Column('kdf_parametros', sa.JSON(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.Column('rotada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claves_cifrado_usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claves_cifrado_usuarios_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('registros_auditoria',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('tipo_recurso', sa.String(length=30), nullable=True),
    sa.Column('recurso_id', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('agente_usuario', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('detalles', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_auditoria_actor_usuario_id'), ['actor_usuario_id'], unique=False)

    op.create_table('tokens_refresco',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens_refresco', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_refresco_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_refresco_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('usuarios_roles',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('rol_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('archivos_compartidos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('archivo_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_destino_id', sa.BigInteger(), nullable=False),
    sa.Column('dek_envuelta_para_destino', sa.LargeBinary(), nullable=False),
    sa.Column('permisos', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['archivo_id'], ['archivos.id'], ),
    sa.ForeignKeyConstraint(['usuario_destino_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archivos_compartidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archivos_compartidos_archivo_id'), ['archivo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_archivos_compartidos_usuario_destino_id'), ['usuario_destino_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivos_compartidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archivos_compartidos_usuario_destino_id'))
        batch_op.drop_index(batch_op.f('ix_archivos_compartidos_archivo_id'))

    op.drop_table('archivos_compartidos')
    op.drop_table('usuarios_roles')
    with op.batch_alter_table('tokens_refresco', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_refresco_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_refresco_token_hash'))

    op.drop_table('tokens_refresco')
    with op.batch_alter_table('registros_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_auditoria_actor_usuario_id'))

    op.drop_table('registros_auditoria')
    with op.batch_alter_table('claves_cifrado_usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claves_cifrado_usuarios_usuario_id'))

    op.drop_table('claves_cifrado_usuarios')
    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archivos_propietario_id'))

    op.drop_table('archivos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_correo'))

    op.drop_table('usuarios')
    op.drop_table('roles')
    with op.batch_alter_table('jwt_lista_negra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jwt_lista_negra_jti'))

    op.drop_table('jwt_lista_negra')
    # ### end Alembic commands ###
